version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      python-development:
        dependency-type: development
  - package-ecosystem: npm
    directory: /site
    schedule:
      interval: weekly
    groups:
      astro:
        patterns: ["astro", "@astrojs/*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

